name: CI/CD Pipeline with Grype

on: [push]
jobs:
  vulnerability_scanning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull alpine:latest
      run: docker pull alpine:latest

    - name: Install grype
      run: |
        curl -sL https://github.com/anchore/grype/releases/download/v0.13.0/grype_0.13.0_linux_amd64.tar.gz | tar -xz -C /tmp
        sudo mv /tmp/grype /usr/local/bin
        sudo chmod +x /usr/local/bin/grype
        
    - name: Run grype and echo the output
      run: |
        grype alpine:latest -o json > grype-report.json
        cat grype-report.json  # Echo the content of the Grype report
