name: Run Grype Scan and Push to MongoDB

on:
  push:
    branches:
      - main

jobs:
  grype_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Grype scan
        id: grype_scan
        run: |
          docker run --rm -v "$(pwd)":/app -w /app/artifacts -u "$(id -u):$(id -g)" anchore/grype:latest --scope all-layers -o json > grype_scan_output.json

      - name: Insert Grype scan output into MongoDB
        uses: mongodb-actions/setup-mongodb@v2
        with:
          mongodb_connection_string: ${{ secrets.MONGODB_CONNECTION_STRING }}  # Use your secret for MongoDB connection string
          mongodb_database_name: "cve_db"
          mongodb_collection_name: "cve_list"
        run: |
          mongoimport --uri=$MONGODB_CONNECTION_STRING --database=$MONGODB_DATABASE_NAME --collection=$MONGODB_COLLECTION_NAME --file=grype_scan_output.json --jsonArray
