name: CI/CD Pipeline with Grype
on:
  push:
    branches:
      - main  # Change this to your main branch
jobs:
  vulnerability_scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Switch to root
        run: sudo -i

      - name: Install grype
        run: |
          curl -sL https://github.com/anchore/grype/releases/download/v0.13.0/grype_0.13.0_linux_amd64.tar.gz | tar -xz -C /tmp
          sudo mv /tmp/grype /usr/local/bin/grype  # Assuming /usr/local/bin is in your PATH

      - name: Run Grype 
        run: /usr/local/bin/grype public.ecr.aws/initializ/go:latest
